### ISSUE TITLE
How to integrate with pkg

### ISSUE THREAD

**Issue by gilbertoalbino** [hetrodoo/hetrodo-node-hide-console-window-napi#1]
Hi, thank you very much for this package.

Could you provide an example of how to integrate with pkg?

**Comment by woodytec** [comment]
Hi,
You can copy this .node `node-hide-console-window.node` in the same folder as your pkg binary.

This file is located in `node_modules\node-hide-console-window\build\Release`

**Comment by hetrodoo** [comment]
Sorry for the late response (that apparently is already resolved thanks @woodytec) but pkg does not automatically include the module into the build? It if doesn't please let me know so I can update the readme!

**Comment by hetrodoo** [comment]
Marked closed for lack of activity.
