### ISSUE TITLE
PKG not finding .node object despite being added as an asset.

### ISSUE THREAD

**Issue by Lucky38i** [hetrodoo/hetrodo-node-hide-console-window-napi#3]
For some reason when building my node project as fully standalone it's not finding the module.
![Screenshot 2022-05-19 at 17 49 03](https://user-images.githubusercontent.com/26572019/169354681-ccdef19d-282b-4a2d-9bff-9ce9a161ae83.png)

my package.json
![Screenshot 2022-05-19 at 17 49 26](https://user-images.githubusercontent.com/26572019/169354745-824d04a7-dd1e-4f74-9cd2-303549b66a18.png)

**Comment by KosiakNet** [comment]
The path to the tmp folder is too long.

**Comment by hetrodoo** [comment]
@Lucky38i Hi this is the issues page for the [node-hide-console-window](https://www.npmjs.com/package/node-hide-console-window) not the [vercel/pkg](https://www.npmjs.com/package/pkg) so i suggest openning your issue [here](https://github.com/vercel/pkg/issues).
