### ISSUE TITLE
Failing to compile with nexe - Unable to find Specified Module process.dlopen()

### ISSUE THREAD

**Issue by lrNas** [hetrodoo/hetrodo-node-hide-console-window-napi#5]
Hello everyone! 
I'm having issues to use node-hide-console-window with nexe. The program run correctly by npm start, but I'm getting the following issue when running the .exe after build:

```
return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: Não foi possível encontrar o módulo especificado. (Unable to find especified Module)
\\?\C:\Arquivos\Workspaces\ManagedByVw\Builded\node_modules\node-hide-console-window\build\Release\node-hide-console-window.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Arquivos\Workspaces\ManagedByVw\Builded\node_modules\node-hide-console-window\index.js:1:36)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) 
```

I've already tryed:
npm i node-hide-console-window
npm rebuild node-hide-console-window
Delete node_modules and package-lock.json
npm cache clean --force
npm update
npm rebuild node-hide-console-window --build-from-source
installed another node version with nvm and switched
reinstalled nexe

I'm using node v14.15.3, npm 6.14.9, Windows 10 x64 22H2 on A10-4800M

My package.json

```
{
  "name": "managedbybe",
  "version": "1.0.0",
  "description": "Backend do ManagedBy",
  "main": "./src/index.js",
  "scripts": {
    "test": "nodemon node ./src/index.js",
    "start": "node ./src/index.js"
  },
  "keywords": [
    "javascript",
    "php",
    "nodejs"
  ],
  "author": "Lucas Rodrigues do Nascimento",
  "license": "ISC",
  "dependencies": {
    "express": "^4.17.3",
    "node-hide-console-window": "^2.1.1",
    "sequelize": "^6.17.0",
    "sequelize-cli": "^6.5.2",
    "systray": "^1.0.5",
    "tedious": "^15.1.2"
  },
  "devDependencies": {
    "nexe": "^4.0.0-rc.2",
    "nodemon": "^2.0.15"
  }
}
```
I'm requiring as this in ./src/index.js:
`const {hideConsole,showConsole} = require("node-hide-console-window");`
I've tried to importe as ConsoleWindow also, still the same.

I'm not sure if it's an node-hide-console-window problem, or node.js or nexe. Please let me know if i'm in the wrong place.

**Comment by hetrodoo** [comment]
Hi! Can you send the nexe build command that you are using?

**Comment by lrNas** [comment]
Yes, and thanks for the fast response:
```
const { compile } = require('nexe')

compile({
  input: './src/index.js',
  name:"./mbbe.exe",
  output:"..\\Builded\\mbbe.exe",
  build: true,
  loglevel:'verbose',
  targets:"windows-x64-14.15.3"
}).then(() => {
  console.log('success')
})
.catch(e=>{
    console.log(e)
})
```

Look like something related as nexe not executing Native Modules, but I still not much sure about it, neither able to solve.

**Comment by lrNas** [comment]
I could work arround it by coping` .*\node_modules\node-hide-console-window\build\Release\node-hide-console-window.node`
to `node_modules\node-hide-console-window.node` inside the .exe generated by Nexe. 

Personally, I don't like so much this approach as it's let part of the arch of the program exposed, and I find less secure (I can be wrong).

In Nexe documentation there are [this info](https://github.com/nexe/nexe/#native-modules) (that you can't bundle native modules) and I just missed.

I also tryed to install [Nexe Natives](https://github.com/nmarus/nexe-natives) but no success.

Thank you for your attention, and I hope this issue can help someone to find a solution faster than me 👍 

Feel free to reopen if you think that it could be improved in future, but I personally think that it's a NEXE question.
