### ISSUE TITLE
Error: Cannot find module './node-hide-console-window

### ISSUE THREAD

**Issue by Zss96** [hetrodoo/hetrodo-node-hide-console-window-napi#7]
npm install node-hide-console-window,build is no files
![image](https://github.com/hetrodoo/hetrodo-node-hide-console-window-napi/assets/53645562/8a45a611-3134-4296-b47a-a55b4520f857)

**Comment by hetrodoo** [comment]
Can you try running npm install and see if any node-gyp related errors occours?

**Comment by hetrodoo** [comment]
Issue closed due to lack of response from the author.
