### ISSUE TITLE
Fail to run npm install node-hide-console-window

### ISSUE THREAD

**Issue by Higanoneko** [hetrodoo/hetrodo-node-hide-console-window-napi#9]
[2023-11-06T12_14_31_203Z-debug-0.log](https://github.com/hetrodoo/node-hide-console-window/files/13266306/2023-11-06T12_14_31_203Z-debug-0.log)
 
like log files shows up

**Comment by hetrodoo** [comment]
node-hide-console-window relies on [node-gyp](https://github.com/nodejs/node-gyp) and by this log file it looks like node-gyp is throwing some errors related with you python installation. 

Make sure you have a **supported python version**, the **node-gyp package** installed globally and **Microsoft Visual Studio** with the **C++ development tools** installed as well.

Take a look at the node-gyp github page for those requirements: https://github.com/nodejs/node-gyp

**Comment by Higanoneko** [comment]
> node-hide-console-window relies on [node-gyp](https://github.com/nodejs/node-gyp) and by this log file it looks like node-gyp is throwing some errors related with you python installation.
> 
> Make sure you have a **supported python version**, the **node-gyp package** installed globally and **Microsoft Visual Studio** with the **C++ development tools** installed as well.
> 
> Take a look at the node-gyp github page for those requirements: https://github.com/nodejs/node-gyp

Fixed by using yarn instead of npm.
thx 4 ur help

**Comment by JoCat** [comment]
I ran into the same problem, decided to review the code to see what the error might be and saw the following:
```
# Make sure we're using the version of pylib in this repo, not one installed
# elsewhere on the system. Also convert to Unix style path on Cygwin systems,
# else the 'gyp' library will not be found
```

Just in case, I tried running it via git bash and everything installed. Perhaps the problem lies in the interaction with `cmd`.

**Comment by JoCat** [comment]
It seems to have something to do with https://github.com/nodejs/node-gyp/issues/2869

**upd.** is solved by installing a more recent version of npm
